version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: surgimap-postgres
    restart: always
    environment:
      POSTGRES_USER: surgimap_user
      POSTGRES_PASSWORD: surgimap_pass
      POSTGRES_DB: surgimap_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
